name: wordle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  lottie: ^1.4.2
  flip_card: ^0.7.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.4.0
  cloud_firestore: ^3.5.1
  animated_flip_counter: ^0.3.3
  flutter_spinkit: ^5.2.1
  google_sign_in: ^5.4.3
  twitter_login: ^3.0.8
  flutter_web_auth: ^0.4.3

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/images/wordle_logo.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
